gre_words = {
    'abate': 'to make or become less in amount, intensity, degree, etc',
    'aberrant': 'deviating from the normal or usual type, as certain animals from '
             'the group in which they are classified',
    'abet': 'to assist or encourage, esp in crime or wrongdoing',
    'abeyance': 'usually preceded by in or into a state of being suspended or put '
             'aside temporarily',
    'abhor': 'to detest vehemently; find repugnant; reject',
    'abide': 'to tolerate; put up with',
    'abject': 'utterly wretched or hopeless',
    'abjure': 'to renounce or retract, esp formally, solemnly, or under oath',
    'abound': 'to exist or occur in abundance; be plentiful',
    'abrasive': 'a substance or material such as sandpaper, pumice, or emery, '
             'used for cleaning, grinding, smoothing, or polishing',
    'abreast': 'alongside each other and facing in the same direction',
    'abscond': 'to run away secretly, esp from an open institution or to avoid '
            'prosecution or punishment',
    'abstain': 'to choose to refrain',
    'abstract': 'having no reference to material objects or specific examples; '
             'not concrete',
    'abstruse': 'not easy to understand; recondite; esoteric',
    'accentuate': 'to stress or emphasize',
    'accessible': 'easy to approach, enter, use, or understand',
    'acclaim': 'to acknowledge publicly the excellence of',
    'accord': 'agreement; conformity; ',
    'acolyte': 'a follower or attendant',
    'acquiesce': 'to comply ; assent without protest',
    'acquisitive': 'inclined or eager to acquire things, esp material possessions',
    'acrimonious': 'characterized by bitterness or sharpness of manner, speech, '
                'temper, etc',
    'acumen': 'the ability to judge well; keen discernment; insight',
    'ad hoc': 'for a particular purpose only; lacking generality or justification',
    'adept': 'very proficient in something requiring skill or manual dexterity',
    'adhere': 'to stick or hold fast',
    'admonish': 'to reprove firmly but not harshly',
    'adroit': 'skilful or dexterous',
    'adulterate': 'to debase by adding inferior material',
    'adverse': 'antagonistic or inimical; hostile',
    'advocate': 'to support or recommend publicly; plead for or speak in favour '
             'of',
    'aesthetic': 'connected with ',
    'affectation': 'an assumed manner of speech, dress, or behaviour, esp one '
                'that is intended to impress others',
    'affinity': 'foll by with or for a natural liking, taste, or inclination '
             'towards a person or thing',
    'affluent': 'rich; wealthy',
    'affront': 'a deliberate insult',
    'aggrandize': 'to increase the power, wealth, prestige, scope, etc, of',
    'agitate': 'to excite, disturb, or trouble ; worry',
    'alacrity': 'liveliness or briskness',
    'alienate': 'to cause to become indifferent, unfriendly, or hostile; estrange',
    'allegorical': 'used in, containing, or characteristic of allegory',
    'alleviate': 'to make easier to bear; lessen; relieve',
    'allude': 'to refer indirectly, briefly, or implicitly',
    'allusive': 'containing or full of allusions',
    'aloof': 'distant, unsympathetic, or supercilious in manner, attitude, or '
          'feeling',
    'altruistic': 'practising altruism; unselfish',
    'amalgamate': 'to combine or cause to combine; unite',
    'ambivalent': 'feeling simultaneously the existence of two opposed and '
               'conflicting attitudes, emotions, etc',
    'ameliorate': 'to make or become better; improve',
    'amenable': 'open or susceptible to suggestion; likely to listen, cooperate, '
             'etc',
    'amend': 'to improve; change for the better',
    'amicable': 'characterized by friendliness',
    'amorphous': 'lacking a definite shape; formless',
    'amplify': 'to increase in size, extent, effect, etc, as by the addition of '
            'extra material; augment; enlarge; expand',
    'anachronistic': 'belonɡinɡ to an earlier period of history',
    'analogous': 'similar or corresponding in some respect',
    'animosity': 'a powerful and active dislike or hostility; enmity',
    'animus': 'intense dislike; hatred; animosity',
    'anoint': 'to smear or rub over with oil or an oily liquid',
    'anomalous': 'deviating from the normal or usual order, type, etc; irregular, '
              'abnormal, or incongruous',
    'antagonize': 'to make hostile; annoy or irritate',
    'antedate': 'to be or occur at an earlier date than',
    'antipathy': 'a feeling of intense aversion, dislike, or hostility',
    'antithesis': 'the exact opposite',
    'apathy': 'absence of interest in or enthusiasm for things generally '
           'considered interesting or moving',
    'aphorism': 'a short pithy saying expressing a general truth; maxim',
    'aplomb': 'equanimity, self-confidence, or self-possession',
    'apogee': 'the highest point',
    'apologist': 'a person who offers a defence by argument',
    'appease': 'to calm, pacify, or soothe, esp by acceding to the demands of',
    'apposite': 'well suited for the purpose; appropriate',
    'apprehension': 'fear or anxiety over what may happen',
    'approbation': 'commendation; praise',
    'appropriate': 'right or suitable; fitting',
    'apropos': 'appropriate; pertinent',
    'apt': 'suitable for the circumstance or purpose; appropriate',
    'arbitrary': 'founded on or subject to personal whims, prejudices, etc; '
              'capricious',
    'arcane': 'requiring secret knowledge to be understood; mysterious; esoteric',
    'archaic': 'belonging to or characteristic of a much earlier period; ancient',
    'archetype': 'a perfect or typical specimen',
    'ardent': 'expressive of or characterized by intense desire or emotion; '
           'passionate',
    'arduous': 'requiring great physical or mental effort; difficult to '
            'accomplish; strenuous',
    'arresting': 'attracting attention; striking',
    'artful': 'cunning or tricky',
    'articulate': 'able to express oneself fluently and coherently',
    'artless': 'free from deceit, guile, or artfulness; ingenuous',
    'ascertain': 'to determine or discover definitely',
    'ascetic': 'a person who practises great self-denial and austerities and '
            'abstains from worldly comforts and pleasures, esp for religious '
            'reasons',
    'ascribe': 'to credit or assign, as to a particular origin or period',
    'aspersion': 'a disparaging or malicious remark; slanderous accusation (esp '
              'in the phrase cast ',
    'assail': 'to attack violently; assault',
    'assertive': "confident and direct in claiming one's rights or putting "
              "forward one's views",
    'assuage': 'to soothe, moderate, or relieve',
    'astringent': 'severe; harsh',
    'astute': 'having insight or acumen; perceptive; shrewd',
    'attenuate': 'to weaken or become weak; reduce in size, strength, density, or '
              'value',
    'attribute': 'usually foll by to to regard as belonging, produced, or '
              'resulting ; ascribe',
    'audacious': 'recklessly bold or daring; fearless',
    'augment': 'to make or become greater in number, amount, strength, etc; '
            'increase',
    'august': 'dignified or imposing',
    'auspicious': 'favourable or propitious',
    'austere': 'stern or severe in attitude or manner',
    'auxiliary': 'secondary or supplementary',
    'avaricious': 'extremely greedy to get and keep riches; miserly',
    'aver': 'to state positively; assert',
    'aversion': 'usually foll by to or for extreme dislike or disinclination; '
             'repugnance',
    'avert': 'to turn away or aside',
    'avid': 'very keen; enthusiastic',
    'axiomatic': 'relating to or resembling an axiom; self-evident',
    'banal': 'lacking force or originality; trite; commonplace',
    'banish': 'to expel from a place, esp by an official decree as a punishment',
    'baroque': 'a style of architecture and decorative art that flourished '
            'throughout europe from the late 16th to the early 18th century, '
            'characterized by extensive ornamentation',
    'barrage': 'the firing of artillery to saturate an area, either to protect '
            'against an attack or to support an advance',
    'barren': 'incapable of producing offspring, seed, or fruit; sterile',
    'base': 'the bottom or supporting part of anything',
    'bawdy': 'containing references to sex, esp to be humorous',
    'befuddled': 'confused, muddled, perplexed',
    'beholden': 'indebted; obliged; under a moral obligation',
    'belie': 'to show to be untrue; contradict',
    'belittle': 'to consider or speak of as less valuable or important than it '
             'really is; disparage',
    'belligerent': 'marked by readiness to fight or argue; aggressive',
    'benchmark': 'a mark on a stone post or other permanent feature, at a point '
              'whose exact elevation and position is known: used as a '
              'reference point in surveying bm',
    'beneficent': 'charitable; generous',
    'benevolent': 'intending or showing goodwill; kindly; friendly',
    'benign': 'showing kindliness; genial',
    'berate': 'to scold harshly',
    'bereft': 'deprived; parted',
    'betray': 'to aid an enemy of ; be a traitor to',
    'blithe': 'very happy or cheerful',
    'bogus': 'spurious or counterfeit; not genuine',
    'boisterous': 'noisy and lively; unrestrained or unruly',
    'bolster': 'to support or reinforce; strengthen',
    'bombastic': 'characterized by, or full of, bombast',
    'boorish': 'ill-mannered, clumsy, or insensitive; rude',
    'bravado': 'vaunted display of courage or self-confidence; swagger',
    'brazen': 'shameless and bold',
    'brevity': 'conciseness of expression; lack of verbosity',
    'bridle': 'a headgear for a horse, etc, consisting of a series of buckled '
           'straps and a metal mouthpiece by which the animal is controlled '
           'through the reins',
    'bromide': 'any salt of hydrobromic acid, containing the monovalent ion br–',
    'brook': 'a natural freshwater stream smaller than a river',
    'bucolic': 'of or characteristic of the countryside or country life; rustic',
    'buoyant': 'able to float in or rise to the surface of a liquid',
    'burgeon': 'often foll by forth or out to sprout',
    'burnish': 'to make or become shiny or smooth by friction; polish',
    'buttress': 'any support or prop',
    'byzantine': 'of, characteristic of, or relating to byzantium or the ',
    'cacophonous': 'jarring in sound; discordant; harsh',
    'cajole': 'to persuade by flattery or pleasing talk to do what one wants; '
           'wheedle; coax',
    'calamitous': 'causing, involving, or resulting in a calamity; disastrous',
    'callow': 'lacking experience of life; immature',
    'calumny': 'the malicious utterance of false charges or misrepresentation; '
            'slander; defamation',
    'candid': 'frank and outspoken',
    'canny': 'shrewd, esp in business; astute or wary; knowing',
    'canonize': 'to declare to be a saint and thus admit to the canon of saints',
    'capitulate': 'to surrender, esp under agreed conditions',
    'capricious': 'characterized by or liable to sudden unpredictable changes in '
               'attitude or behaviour; impulsive; fickle',
    'captious': 'apt to make trivial criticisms; fault-finding; carping',
    'caricature': 'a pictorial, written, or acted representation of a person, '
               'which exaggerates his characteristic traits for comic effect',
    'castigate': 'to rebuke or criticize in a severe manner',
    'cataclysmic': 'of or relating to a violent upheaval',
    'catastrophic': 'involving or causing a sudden terrible disaster, esp one '
                 'that causes suffering for a lot of people',
    'cathartic': 'purgative',
    'caustic': 'capable of burning or corroding by chemical action',
    'cavalier': 'showing haughty disregard; offhand',
    'cease': 'when tr, may take a gerund or an infinitive as object to bring or '
          'come to an end; desist from; stop',
    'censor': 'a person authorized to examine publications, theatrical '
           'presentations, films, letters, etc, in order to suppress in whole '
           'or part those considered obscene, politically unacceptable, etc',
    'censure': 'severe disapproval; harsh criticism',
    'cerebral': 'of or relating to the cerebrum or to the entire brain',
    'chagrin': 'a feeling of annoyance or mortification',
    'champion': 'a person who has defeated all others in a competition',
    'chary': 'wary; careful',
    'chastise': 'to discipline or punish, esp by beating',
    'chauvinistic': 'aggressively or fanatically patriotic; jingoistic',
    'check': 'to pause or cause to pause, esp abruptly',
    'cherish': 'to show great tenderness for; treasure',
    'chicanery': 'verbal deception or trickery, esp in legal quibbling; dishonest '
              'or sharp practice',
    'chivalrous': 'gallant; courteous',
    'churlish': 'rude or surly',
    'circumscribe': 'to restrict within limits',
    'circumspect': 'cautious, prudent, or discreet',
    'circumstantial': 'of or dependent on circumstances',
    'clamorous': 'loud and persistent',
    'clandestine': 'secret and concealed, often for illicit reasons; furtive',
    'clangor': 'a continuous loud banging or ringing sound',
    'cloak': 'a wraplike outer garment fastened at the throat and falling '
          'straight from the shoulders',
    'cloying': 'initially pleasurable or sweet but wearying in excess',
    'cluster': 'a number of things growing, fastened, or occurring close together',
    'coalesce': 'to unite or come together in one body or mass; merge; fuse; '
             'blend',
    'coercion': 'the act or power of coercing',
    'cogent': 'compelling belief or assent; forcefully convincing',
    'cogitate': 'think deeply about something; meditate or reflect',
    'coherent': 'capable of logical and consistent speech, thought, etc',
    'coin': 'a metal disc or piece used as money',
    'collaborate': 'often foll by on, with, etc to work with another or others on '
                'a joint project',
    'collude': 'to conspire together, esp in planning a fraud',
    'comity': 'mutual civility; courtesy',
    'commence': 'to start or begin; come or cause to come into being, operation, '
             'etc',
    'commensurate': 'having the same extent or duration',
    'commiserate': 'when intr, usually foll by with to feel or express sympathy '
                'or compassion',
    'compelling': 'arousing or denoting strong interest, esp admiring interest',
    'competent': 'having sufficient skill, knowledge, etc; capable',
    'complacent': 'pleased or satisfied',
    'complementary': 'acting as or forming a complement; completing',
    'comply': 'to act in accordance with rules, wishes, etc; be obedient',
    'compound': 'a substance that contains atoms of two or more chemical elements '
             'held together by chemical bonds',
    'compromise': 'settlement of a dispute by concessions on both or all sides',
    'conciliatory': 'intended to placate or reconcile',
    'conclusive': 'putting an end to doubt; decisive; final',
    'condone': 'to overlook or forgive',
    'conducive': 'making a certain situation or outcome likely or possible',
    'conflagration': 'a large destructive fire',
    'confound': 'to astound or perplex; bewilder',
    'congenial': 'friendly, pleasant, or agreeable',
    'conjectural': 'based on how something seems and not on proof',
    'connoisseur': 'a person with special knowledge or appreciation of a field, '
                'esp in the arts',
    'consensus': 'general or widespread agreement',
    'conspicuous': 'clearly visible; obvious or showy',
    'conspire': 'to plan or agree on together in secret',
    'construe': 'to interpret the meaning of',
    'contemplate': 'to think about intently and at length; consider calmly',
    'contemporary': 'belonging to the same age; living or occurring in the same '
                 'period of time',
    'contempt': 'the attitude or feeling of a person towards a person or thing '
             'that he considers worthless or despicable; scorn',
    'contend': 'often foll by with to struggle in rivalry, battle, etc; vie',
    'content': 'everything that is inside a container',
    'contentious': 'tending to argue or quarrel',
    'contravene': 'to come into conflict with or infringe',
    'contretemps': 'an awkward or difficult situation or mishap',
    'contrite': 'full of guilt or regret; remorseful',
    'conundrum': 'a riddle, esp one whose answer makes a play on words',
    'convalescent': 'recovering from illness',
    'conventional': 'following the accepted customs and proprieties, esp in a way '
                 'that lacks originality',
    'conviction': 'the state or appearance of being convinced',
    'convivial': 'sociable; jovial or festive',
    'convoluted': 'difficult to comprehend; involved',
    'copious': 'abundant; extensive in quantity',
    'cordial': 'warm and friendly',
    'corporeal': 'of the nature of the physical body; not spiritual',
    'correlate': 'to place or be placed in a mutual, complementary, or reciprocal '
              'relationship',
    'corroborate': 'to confirm or support, esp by providing fresh evidence',
    'cosmopolitan': 'a person who has lived and travelled in many countries, esp '
                 'one who is free of national prejudices',
    'countenance': "the face, esp when considered as expressing a person's "
                'character or mood',
    'counterfeit': 'made in imitation of something genuine with the intent to '
                'deceive or defraud; forged',
    'covert': 'concealed or secret',
    'covet': 'to wish, long, or crave for',
    'coy': 'affectedly demure, esp in a playful or provocative manner',
    'crafty': 'skilled in deception; shrewd; cunning',
    'craven': 'cowardly; mean-spirited',
    'credible': 'capable of being believed',
    'crestfallen': 'dejected, depressed, or disheartened',
    'croon': 'to sing or speak in a soft low tone',
    'cumbersome': 'awkward because of size, weight, or shape',
    'cunning': 'crafty and shrewd, esp in deception; sly',
    'curb': 'something that restrains or holds back',
    'curmudgeon': 'a surly or miserly person',
    'cursory': 'hasty and usually superficial; quick',
    'curtail': 'to cut short; abridge',
    'daunting': 'causing fear or discouragement; intimidating',
    'dawdle': 'to be slow or lag behind',
    'dearth': 'an inadequate amount, esp of food; scarcity',
    'debase': 'to lower in quality, character, or value, as by adding cheaper '
           'metal to coins; adulterate',
    'debilitating': 'tending to weaken or enfeeble',
    'debunk': 'to expose the pretensions or falseness of, esp by ridicule',
    'decadent': 'characterized by decay or decline, as in being self-indulgent or '
             'morally corrupt',
    'decipher': 'to determine the meaning of',
    'decorum': 'propriety, esp in behaviour or conduct',
    'decry': 'to express open disapproval of; disparage',
    'defame': 'to attack the good name or reputation of; slander; libel',
    'deference': 'submission to or compliance with the will, wishes, etc, of '
              'another',
    'deflect': 'to turn or cause to turn aside from a course; swerve',
    'deft': 'quick and neat in movement; nimble; dexterous',
    'deify': 'to exalt to the position of a god or personify as a god',
    'deleterious': 'harmful; injurious; hurtful',
    'deliberate': 'carefully thought out in advance; planned; studied; '
               'intentional',
    'delineate': 'to trace the shape or outline of; sketch',
    'delusion': 'a mistaken or misleading opinion, idea, belief, etc',
    'demur': 'to raise objections or show reluctance; object',
    'denigrate': 'to belittle or disparage the character of; defame',
    'denounce': 'to deplore or condemn openly or vehemently',
    'deportment': 'the manner in which a person behaves',
    'depose': 'to remove from an office or position, esp one of power or rank',
    'depravity': 'the state or an instance of moral corruption',
    'deprecate': 'to express disapproval of; protest against',
    'deride': 'to speak of or treat with contempt, mockery, or ridicule',
    'derivative': 'resulting from derivation; derived',
    'desiccate': 'to remove most of the water from ; dehydrate',
    'despotic': 'unfair and cruel in the exercise of power',
    'desultory': 'passing or jumping from one thing to another, esp in a fitful '
              'way; unmethodical; disconnected',
    'deter': 'to discourage or prevent, usually by instilling fear, doubt, or '
          'anxiety',
    'detract': 'when intr, usually foll by from to take away a part ; diminish',
    'detrimental': 'when postpositive, foll by to harmful; injurious',
    'deviate': 'to differ or diverge or cause to differ or diverge, as in belief '
            'or thought',
    'devious': 'not sincere or candid; deceitful; underhand',
    'dexterous': 'possessing or done with dexterity',
    'diatribe': 'a bitter or violent criticism or attack; denunciation',
    'dichotomy': 'division into two parts or classifications, esp when they are '
              'sharply distinguished or opposed',
    'dictate': 'to say aloud for mechanical recording or verbatim transcription '
            'by another person',
    'dictum': 'a formal or authoritative statement or assertion; pronouncement',
    'didactic': 'intended to instruct, esp excessively',
    'diffident': 'lacking self-confidence; timid; shy',
    'diffuse': 'to spread or cause to spread in all directions',
    'digression': 'an act or instance of digressing from a main subject in speech '
               'or writing',
    'dilatory': 'tending or inclined to delay or waste time',
    'dilettante': 'a person whose interest in a subject is superficial rather '
               'than professional',
    'diminutive': 'very small; tiny',
    'dirge': 'a chant of lamentation for the dead',
    'discernible': 'able to be discerned; perceptible',
    'disciple': 'a follower of the doctrines of a teacher or a school of thought',
    'discomfit': 'to make uneasy, confused, or embarrassed',
    'disconcerting': 'causing a feeling of disturbance, embarrassment, or '
                  'confusion; perturbing; worrying',
    'discount': 'to leave out of account as being unreliable, prejudiced, or '
             'irrelevant',
    'discreet': 'careful to avoid social embarrassment or distress, esp by '
             'keeping confidences secret; tactful',
    'discrepancy': 'a conflict or variation, as between facts, figures, or claims',
    'disdain': 'a feeling or show of superiority and dislike; contempt; scorn',
    'disentangle': 'to release or become free from entanglement or confusion',
    'disingenuous': 'not sincere; lacking candour',
    'disinterested': 'free from bias or partiality; objective',
    'dismantle': 'to take apart',
    'disparate': 'utterly different or distinct in kind',
    'dispense': 'to give out or issue in portions',
    'disperse': 'to scatter; distribute over a wide area',
    'dissemble': 'to conceal by pretence',
    'disseminate': 'to distribute or scatter about; diffuse',
    'dissent': 'to have a disagreement or withhold assent',
    'dissident': 'disagreeing; dissenting',
    'distend': 'to expand or be expanded by or as if by pressure from within; '
            'swell; inflate',
    'distort': 'to twist or pull out of shape; make bent or misshapen; contort; '
            'deform',
    'distressed': 'much troubled; upset; afflicted',
    'divergent': 'diverging or causing divergence',
    'divulge': 'to make known ; disclose',
    'doctrinaire': 'stubbornly insistent on the observation of the niceties of a '
                'theory, esp without regard to practicality, suitability, etc',
    'documentary': 'also: documental',
    'dogged': 'obstinately determined; wilful or tenacious',
    'dogmatic': 'forcibly asserted as if authoritative and unchallengeable',
    'dormant': 'quiet and inactive, as during sleep',
    'dowdy': 'drab, unflattering, and old-fashioned',
    'draconian': 'of or relating to draco, 7th-century athenian statesman and '
              'lawmaker, or his code of laws, which prescribed death for '
              'almost every offence',
    'droll': 'amusing in a quaint or odd manner; comical',
    'dubious': 'marked by or causing doubt',
    'dupe': 'a person who is easily deceived',
    'duplicitous': 'marked by deliberate deceptiveness especially by pretending '
                'one set of feelings and acting under the influence of another',
    'duress': 'compulsion by use of force or threat; constraint; coercion',
    'dutiful': 'exhibiting or having a sense of duty',
    'dwindling': 'growing less in size, intensity, or number until there is '
              'nothing or almost nothing left; diminishing or shrinking '
              'gradually',
    'ebullient': 'overflowing with enthusiasm or excitement; exuberant',
    'eccentric': 'deviating or departing from convention, esp in a bizarre '
              'manner; irregular or odd',
    'echelon': 'a level of command, responsibility, etc',
    'eclectic': 'selecting what seems best from various styles, doctrines, ideas, '
             'methods, etc',
    'eclipse': 'the period of time during which such a phenomenon occurs',
    'economy': 'careful management of resources to avoid unnecessary expenditure '
            'or waste; thrift',
    'edify': 'to improve the morality, intellect, etc, of, esp by instruction',
    'efficacious': 'capable of or successful in producing an intended result; '
                'effective as a means, remedy, etc',
    'effrontery': 'shameless or insolent boldness',
    'egalitarian': 'of, relating to, or upholding the doctrine of the equality of '
                'mankind and the desirability of political, social, and '
                'economic equality',
    'egregious': 'outstandingly bad; flagrant',
    'elaborate': 'planned or executed with care and exactness; detailed',
    'elated': 'full of high spirits, exhilaration, pride or optimism; very happy',
    'elementary': 'not difficult; simple; rudimentary',
    'elicit': 'to give rise to; evoke',
    'elitist': 'adhering to or promoting the belief that society should be '
            'governed by a select group of gifted and highly educated '
            'individuals',
    'eloquent': 'characterized by fluency and persuasiveness',
    'elucidate': 'to make clear ; clarify',
    'elusive': 'difficult to catch',
    'embellish': 'to improve or beautify by adding detail or ornament; adorn',
    'empathetic': "having the ability to share another person's or emotions as if "
               'they were your own',
    'empirical': 'derived from or relating to experiment and observation rather '
              'than theory',
    'emulate': 'to attempt to equal or surpass, esp by imitation',
    'enchant': 'to cast a spell on; bewitch',
    'encroach': 'often foll by on or upon to intrude gradually, stealthily, or '
             'insidiously upon the rights, property, etc, of another',
    'encyclopedic': 'of, characteristic of, or relating to an encyclopedia',
    'endemic': 'present within a localized area or peculiar to persons in such an '
            'area',
    'endow': 'to provide with or bequeath a source of permanent income',
    'enervate': 'to deprive of strength or vitality; weaken physically or '
             'mentally; debilitate',
    'engender': 'to bring about or give rise to; produce or cause',
    'enigmatic': 'difficult to understand because it is mysterious, puzzling or '
              'ambiguous',
    'enmity': 'a feeling of hostility or ill will, as between enemies',
    'ennui': 'a feeling of listlessness and general dissatisfaction resulting '
          'from lack of activity or excitement',
    'ensue': 'to follow; come next or afterwards',
    'entitled': 'having a title or name',
    'entreat': 'to ask earnestly; beg or plead with; implore',
    'entrenched': 'an ',
    'ephemeral': 'lasting for only a short time; transitory; short-lived',
    'equanimity': 'calmness of mind or temper; composure',
    'equitable': 'impartial or reasonable; fair; just',
    'equivocate': 'to use vague or ambiguous language, esp in order to avoid '
               'speaking directly or honestly; hedge',
    'eradicate': 'to obliterate; stamp out',
    'erratic': 'irregular in performance, behaviour, or attitude; inconsistent '
            'and unpredictable',
    'erstwhile': 'former; one-time',
    'erudite': 'having or showing extensive scholarship; learned',
    'escalate': 'to increase or be increased in extent, intensity, or magnitude',
    'eschew': 'to keep clear of or abstain from ; shun; avoid',
    'esoteric': 'restricted to or intended for an enlightened or initiated '
             'minority, esp because of abstruseness or obscurity',
    'estimable': 'worthy of respect; deserving of admiration',
    'estranged': "separated and living apart from one's spouse",
    'euphemism': 'an inoffensive word or phrase substituted for one considered '
              'offensive or hurtful, esp one concerned with religion, sex, '
              'death, or excreta',
    'euphoric': 'elated, enthusiastic, full of euphoria',
    'evade': 'to get away from or avoid ; escape',
    'evanescent': 'passing out of sight; fading away; vanishing',
    'evasive': 'tending or seeking to evade; avoiding the issue; not '
            'straightforward',
    'evoke': 'to call or summon up, esp from the past',
    'exacerbate': 'to make more intense; aggravate',
    'exacting': 'making rigorous or excessive demands',
    'exasperated': 'greatly irritated or annoyed; infuriated',
    'excoriate': 'to strip from ; flay',
    'exculpate': 'to free from blame or guilt; vindicate or exonerate',
    'exegesis': '',
    'exhaustive': 'comprehensive in scope; thorough',
    'exhilarating': 'causing strong feelings of excitement and happiness',
    'exhort': 'to urge or persuade earnestly',
    'exigent': 'urgent; pressing',
    'exonerate': 'to clear or absolve from blame or a criminal charge',
    'exorbitant': 'in excess of what is reasonable; excessive; extravagant; '
               'immoderate',
    'exotic': 'originating in a foreign country, esp one in the tropics; not '
           'native',
    'expatiate': 'foll by on or upon to enlarge at length or in detail; elaborate',
    'expedient': 'suitable to the circumstances; appropriate',
    'expedite': 'to hasten the progress of; hasten or assist',
    'explicable': 'capable of being explained',
    'exploitative': 'if you describe something as ',
    'extant': 'still in existence; surviving',
    'extemporize': 'to perform, speak, or compose without planning or preparation',
    'extol': 'to praise lavishly; exalt',
    'extraneous': 'not essential',
    'extrapolate': 'to infer by using but not strictly deducing from the known '
                'facts',
    'extravagant': 'spending money excessively or immoderately',
    'fabricate': 'to make, build, or construct',
    'facetious': 'characterized by levity of attitude and love of joking',
    'facility': 'ease of action or performance; freedom from difficulty',
    'factious': 'given to, producing, or characterized by faction',
    'fallacious': 'containing or involving a fallacy; illogical; erroneous',
    'fallible': 'capable of being mistaken; erring',
    'fallow': 'left unseeded after being ploughed and harrowed to regain '
           'fertility for a crop',
    'falter': 'to be hesitant, weak, or unsure; waver',
    'fanciful': 'not based on fact; dubious or imaginary',
    'fastidious': 'very critical; hard to please',
    'fathom': 'a unit of length equal to six feet, used to measure depths of '
           'water',
    'fawn': 'a young deer of either sex aged under one year',
    'feasible': 'able to be done or put into effect; possible',
    'feckless': 'feeble; weak; ineffectual; irresponsible',
    'fecund': 'greatly productive; fertile',
    'feeble': 'lacking in physical or mental strength; frail; weak',
    'feign': 'to put on a show of ; pretend',
    'feint': 'a mock attack or movement designed to distract an adversary, as in '
          'a military manoeuvre or in boxing, fencing, etc',
    'felicitous': 'well-chosen; apt',
    'fervent': 'intensely passionate; ardent',
    'fester': 'to form or cause to form pus',
    'fickle': 'changeable in purpose, affections, etc; capricious',
    'figurative': 'of the nature of, resembling, or involving a figure of speech; '
               'not literal; metaphorical',
    'finicky': 'excessively particular, as in tastes or standards; fussy',
    'fitful': 'characterized by or occurring in irregular spells',
    'flagrant': 'openly outrageous',
    'flamboyant': 'elaborate or extravagant; florid; showy',
    'fledgling': 'a young bird that has just fledged',
    'florid': 'having a red or flushed complexion',
    'flout': 'when intr, usually foll by at to show contempt',
    'flummoxed': 'perplexed or bewildered',
    'flustered': 'in a state of confusion or agitation',
    'foil': 'to baffle or frustrate',
    'foment': 'to encourage or instigate ; stir up',
    'foolhardy': 'heedlessly rash or adventurous',
    'forbear': 'when intr, often foll by from or an infinitive to cease or '
            'refrain',
    'forebode': 'to warn of or indicate in advance',
    'foreseeable': 'able to be known beforehand',
    'forestall': 'to delay, stop, or guard against beforehand',
    'forgo': 'to give up or do without',
    'forsake': 'to abandon',
    'fortitude': 'strength and firmness of mind; resolute endurance',
    'fortuitous': 'happening by chance, esp by a lucky chance',
    'fractious': 'irritable',
    'frailty': 'physical or moral weakness',
    'frank': 'honest and straightforward in speech or attitude',
    'fraught': 'and foll by with filled or charged; attended',
    'fret': 'to distress or be distressed; worry',
    'frivolous': 'not serious or sensible in content, attitude, or behaviour; '
              'silly',
    'fruitful': 'bearing fruit in abundance',
    'fulcrum': 'the pivot about which a lever turns',
    'fungible': 'moveable perishable goods of a sort that may be estimated by '
             'number or weight, such as grain, wine, etc',
    'furtive': 'characterized by stealth',
    'futile': 'having no effective result; unsuccessful',
    'gaffe': 'a social blunder, esp a tactless remark',
    'gainsay': 'deny or contradict (a fact or statement)',
    'galvanize': 'to stimulate to action; excite; startle',
    'gauche': 'lacking ease of manner; tactless',
    'gawky': 'clumsy or ungainly; awkward',
    'germane': 'usually foll by to related ; akin; relevant',
    'glib': 'fluent and easy, often in an insincere or deceptive way',
    'gloat': 'often foll by over to dwell with malevolent smugness or exultation',
    'glum': 'silent or sullen',
    'goad': 'a sharp pointed stick for urging on cattle, etc',
    'gratify': 'to satisfy or please',
    'gratuitous': 'given or received without payment or obligation',
    'gregarious': 'enjoying the company of others',
    'grievance': 'a real or imaginary wrong causing resentment and regarded as '
              'grounds for complaint',
    'grovel': 'to humble or abase oneself, as in making apologies or showing '
           'respect',
    'grumble': 'to utter in a nagging or discontented way',
    'gullible': 'easily taken in or tricked',
    'hackneyed': 'used so often as to be trite, dull, and stereotyped',
    'hamper': 'to prevent the progress or free movement of',
    'haphazard': 'at random',
    'harangue': 'to address in an angry, vehement, or forcefully persuasive way',
    'harbinger': 'a person or thing that announces or indicates the approach of '
              'something; forerunner',
    'harrowing': 'emotionally distressing or vexing',
    'haughty': 'having or showing arrogance',
    'headstrong': 'self-willed; obstinate',
    'heady': 'intoxicating',
    'heed': 'close and careful attention; notice',
    'heterodox': 'at variance with established, orthodox, or accepted doctrines '
              'or beliefs',
    'heterogeneous': 'composed of unrelated or differing parts or elements',
    'hidebound': 'restricted by petty rules, a conservative attitude, etc',
    'hinder': 'to be or get in the way of ; hamper',
    'histrionic': 'excessively dramatic, insincere, or artificial',
    'hodgepodge': 'a jumbled mixture',
    'homogeneous': 'composed of similar or identical parts or elements',
    'humdrum': 'ordinary; dull',
    'hyperbole': 'a deliberate exaggeration used for effect',
    'hypocrite': 'a person who pretends to be what he is not',
    'hysterical': 'of or suggesting hysteria',
    'iconoclastic': 'involving or tending towards attacks on established or '
                 'traditional concepts, principles, laws, etc',
    'ideologue': 'an ideology is a set of conscious and unconscious ideas that '
              "constitute one's goals, expectations, and actions",
    'idiosyncratic': 'of or relating to idiosyncrasy; characteristic of a '
                  'specific person',
    'illusory': 'producing, produced by, or based on illusion; deceptive or '
             'unreal',
    'imbroglio': 'a confused or perplexing political or interpersonal situation',
    'imminent': 'liable to happen soon; impending',
    'immure': '(archaic (or literary) to enclose within or as if within walls; '
           'imprison',
    'immutable': 'unchanging through time; unalterable; ageless',
    'impair': 'to reduce or weaken in strength, quality, etc',
    'impede': 'to restrict or retard in action, progress, etc; hinder; obstruct',
    'impediment': 'a hindrance or obstruction',
    'impenetrable': 'incapable of being pierced through or penetrated',
    'imperative': 'extremely urgent or important; essential',
    'imperious': 'domineering; arrogant; overbearing',
    'impertinent': 'rude; insolent; impudent',
    'imperturbable': 'not easily perturbed; calm; unruffled',
    'impervious': 'not able to be penetrated, as by water, light, etc; '
               'impermeable',
    'impetuous': 'liable to act without consideration; rash; impulsive',
    'implacable': 'incapable of being placated or pacified; unappeasable',
    'implicit': 'not explicit; implied; indirect',
    'impolitic': 'not politic or expedient; unwise',
    'improvise': 'to perform or make quickly from materials and sources '
              'available, without previous planning',
    'impudent': 'mischievous, impertinent, or disrespectful',
    'impugn': 'to challenge or attack as false; assail; criticize',
    'impulsive': 'characterized by actions based on sudden desires, whims, or '
              'inclinations rather than careful thought',
    'inalienable': 'not able to be transferred to another; not alienable',
    'inborn': 'existing from birth; congenital; innate',
    'incendiary': 'of or relating to the illegal burning of property, goods, etc',
    'incessant': 'not ceasing; continual',
    'inchoate': 'just beginning; incipient',
    'incidental': 'happening in connection with or resulting from something more '
               'important; casual or fortuitous',
    'incite': 'to stir up or provoke to action',
    'inclined': 'often foll by to having a disposition; tending',
    'incongruous': 'when postpositive, foll by with or to incompatible with ; '
                'inappropriate',
    'incontrovertible': 'incapable of being contradicted or disputed; undeniable',
    'incredulous': 'not prepared or willing to believe ; unbelieving',
    'indecorous': 'improper or ungraceful; unseemly',
    'indefatigable': 'unable to be tired out; unflagging',
    'indefinite': 'not certain or determined; unsettled',
    'indictment': 'a formal written charge of crime formerly referred to and '
               'presented on oath by a grand jury',
    'indignant': 'feeling or showing indignation',
    'indiscriminate': 'lacking discrimination or careful choice; random or '
                   'promiscuous',
    'indispensable': 'absolutely necessary; essential',
    'indolent': 'disliking work or effort; lazy; idle',
    'induce': 'to persuade or use influence on',
    'industrious': 'hard-working, diligent, or assiduous',
    'ineluctable': 'incapable of being avoided; inescapable',
    'inept': 'awkward, clumsy, or incompetent',
    'infelicity': 'the state or quality of being unhappy or unfortunate',
    'inform': 'to give ',
    'ingenious': 'possessing or done with ingenuity; skilful or clever',
    'ingenuous': 'naive, artless, or innocent',
    'ingrained': 'deeply impressed or instilled',
    'inhibit': 'to restrain or hinder',
    'inimical': 'adverse or unfavourable',
    'innocuous': 'having little or no adverse or harmful effect; harmless',
    'inquisitive': 'excessively curious, esp about the affairs of others; prying',
    'inscrutable': 'incomprehensible; mysterious or enigmatic',
    'insidious': 'stealthy, subtle, cunning, or treacherous',
    'insipid': 'lacking spirit; boring',
    'insolent': 'offensive, impudent, or disrespectful',
    'insular': 'of, relating to, or resembling an island',
    'intelligible': 'able to be understood; comprehensible',
    'interchangeable': 'able to be interchanged; exchangeable',
    'intermediary': 'a person who acts as a mediator or agent between parties',
    'interminable': 'endless or seemingly endless because of monotony or tiresome '
                 'length',
    'intermittent': 'occurring occasionally or at regular or irregular intervals; '
                 'periodic',
    'intimate': 'characterized by a close or warm personal relationship',
    'intransigent': 'not willing to compromise; obstinately maintaining an '
                 'attitude',
    'intrepid': 'fearless; daring; bold',
    'intrigue': 'to make interested or curious',
    'intrinsic': 'of or relating to the essential nature of a thing; inherent',
    'intuitive': 'resulting from intuition',
    'inundate': 'to cover completely with water; overflow; flood; swamp',
    'invasive': 'of or relating to an invasion, intrusion, etc',
    'inveigle': 'to lead or persuade by cleverness or trickery; cajole',
    'inveterate': 'long established, esp so as to be deep-rooted or ingrained',
    'invidious': 'incurring or tending to arouse resentment, unpopularity, etc',
    'invigorate': 'to give vitality and vigour to; animate; brace; refresh',
    'inviolate': 'free from violation, injury, disturbance, etc',
    'irascible': 'easily angered; irritable',
    'ire': 'anger; wrath',
    'irksome': 'causing vexation, annoyance, or boredom; troublesome or tedious',
    'ironclad': 'covered or protected with iron',
    'irresolute': 'lacking resolution; wavering; hesitating',
    'irreverent': 'without due respect or veneration; disrespectful; flippant',
    'itinerant': 'itinerating',
    'jeopardize': 'to risk; hazard',
    'jettison': 'to throw away; abandon',
    'jocund': 'of a humorous temperament; merry',
    'judicious': 'having or proceeding from good judgment',
    'keen': 'eager or enthusiastic',
    'laconic': 'using few words; terse',
    'lament': 'to feel or express sorrow, remorse, or regret',
    'lampoon': 'a satire in prose or verse ridiculing a person, literary work, '
            'etc',
    'languid': 'without energy or spirit',
    'languish': 'to lose or diminish in strength or energy',
    'largesse': 'the generous bestowal of gifts, favours, or money',
    'lassitude': 'physical or mental weariness',
    'latitude': 'an angular distance in degrees north or south of the equator, '
             'equal to the angle subtended at the centre of the globe by the '
             'meridian between the equator and the point in question',
    'laudable': 'deserving or worthy of praise; admirable; commendable',
    'lavish': 'prolific, abundant, or profuse',
    'lax': 'lacking firmness; not strict',
    'lethargic': 'lacking energy or enthusiasm',
    'levity': 'inappropriate lack of seriousness',
    'liability': 'the state of being liable',
    'libertine': 'a morally dissolute person',
    'limpid': 'clear or transparent',
    'lionize': 'to treat as or make into a celebrity',
    'loathe': 'to feel strong hatred or disgust for',
    'loquacious': 'characterized by or showing a tendency to talk a great deal',
    'lucid': 'readily understood; clear',
    'lucrative': 'producing a profit; profitable; remunerative',
    'lugubrious': 'excessively mournful; doleful',
    'lull': 'to soothe by soft sounds or motions',
    'macabre': 'gruesome; ghastly; grim',
    'magisterial': 'commanding; authoritative',
    'magnanimous': 'generous and noble',
    'makeshift': 'serving as a temporary or expedient means, esp during an '
              'emergency',
    'malevolent': 'wishing or appearing to wish evil to others; malicious',
    'malfeasance': 'the expressions misfeasance and nonfeasance, and '
                'occasionally ',
    'malign': 'evil in influence, intention, or effect',
    'malleable': 'able to be worked, hammered, or shaped under pressure or blows '
              'without breaking',
    'manacle': 'a shackle, handcuff, or fetter, used to secure the hands of a '
            'prisoner, convict, etc',
    'manifest': 'easily noticed or perceived; obvious; plain',
    'marginalize': 'to relegate to the fringes, out of the mainstream; make seem '
                'unimportant',
    'martinet': 'a person who maintains strict discipline, esp in a military '
             'force',
    'mawkish': 'falsely sentimental, esp in a weak or maudlin way',
    'mediate': 'to intervene in order to bring about agreement',
    'mendacity': 'the tendency to be untruthful',
    'mercenary': 'influenced by greed or desire for gain',
    'mercurial': 'of, like, containing, or relating to mercury',
    'meritorious': 'praiseworthy; showing merit',
    'metaphorical': 'of or relating to figures of speech in which a word or '
                 'phrase is applied to an object or action that it does not '
                 'literally denote; figurative',
    'meticulous': 'very precise about details, even trivial ones; painstaking',
    'mimic': 'to imitate, esp for satirical effect; ape',
    'minute': 'a period of time equal to 60 seconds; one sixtieth of an hour',
    'misanthropic': 'showing dislike or distrust of other people or mankind in '
                 'general',
    'miscreant': 'a wrongdoer or villain',
    'miserly': 'of or resembling a miser; avaricious',
    'misnomer': 'an incorrect or unsuitable name or term for a person or thing',
    'mitigate': 'to make or become less severe or harsh; moderate',
    'modest': "having or expressing a humble opinion of oneself or one's "
           'accomplishments or abilities',
    'modish': 'in the current fashion or style; contemporary',
    'mollify': 'to pacify; soothe',
    'momentary': 'lasting for only a moment; temporary',
    'monotonous': 'dull and tedious, esp because of repetition',
    'mordant': 'sarcastic or caustic',
    'morose': 'ill-tempered or gloomy',
    'multifaceted': 'having many facets',
    'mundane': 'everyday, ordinary, or banal',
    'munificent': 'very generous; bountiful',
    'mutiny': 'open rebellion against constituted authority, esp by seamen or '
           'soldiers against their officers',
    'myopic': 'suffering from myopia',
    'nadir': 'the point on the celestial sphere directly below an observer and '
          'diametrically opposite the zenith',
    'naive': 'having or expressing innocence and credulity; ingenuous',
    'narcissism': 'an exceptional interest in or admiration for oneself, esp '
               "one's physical appearance",
    'nascent': 'starting to grow or develop; being born',
    'negligent': 'habitually neglecting duties, responsibilities, etc; lacking '
              'attention, care, or concern; neglectful',
    'neophyte': 'a person newly converted to a religious faith',
    'nettlesome': 'causing or susceptible to irritation',
    'neutralize': 'to render or become ineffective or neutral by counteracting, '
               'mixing, etc; nullify',
    'nimble': 'agile, quick, and neat in movement',
    'noble': 'of or relating to a hereditary class with special social or '
          'political status, often derived from a feudal period',
    'nominal': 'in name only; theoretical',
    'nonchalant': 'casually unconcerned or indifferent; uninvolved',
    'nonplussed': 'confused and unsure how to react',
    'noxious': 'poisonous or harmful',
    'nullify': 'to render legally void or of no effect',
    'numinous': 'denoting, being, or relating to a numen; divine',
    'obdurate': 'not easily moved by feelings or supplication; hardhearted',
    'obeisance': 'an attitude of deference or homage',
    'objurgation': 'the act of scolding or reprimanding strongly',
    'oblivious': 'foll by to or of unaware or forgetful',
    'obscure': 'unclear or abstruse',
    'obsequious': 'obedient or attentive in an ingratiating or servile manner',
    'obsolete': 'out of use or practice; not current',
    'obstinate': 'adhering fixedly to a particular opinion, attitude, course of '
              'action, etc',
    'obstreperous': 'noisy or rough, esp in resisting restraint or control',
    'obviate': 'to avoid or prevent',
    'occlude': 'to block or stop up ; obstruct',
    'odious': 'offensive; repugnant',
    'officious': 'unnecessarily or obtrusively ready to offer advice or services',
    'ominous': 'foreboding evil',
    'omit': 'to neglect to do or include',
    'omnipresent': 'present in all places at the same time',
    'omniscient': 'having infinite knowledge or understanding',
    'onerous': 'laborious or oppressive',
    'opaque': 'not transmitting light; not transparent or translucent',
    'opportunistic': 'of or characterized by opportunism',
    'opprobrium': 'the state of being abused or scornfully criticized',
    'ornate': 'heavily or elaborately decorated',
    'ostentatious': 'characterized by pretentious, showy, or vulgar display',
    'oust': 'to force out of a position or place; supplant or expel',
    'outlandish': 'grotesquely unconventional in appearance, habits, etc',
    'outstrip': 'to surpass in a sphere of activity, competition, etc',
    'overt': 'open to view; observable',
    'pacify': 'to calm the anger or agitation of; mollify',
    'painstaking': 'extremely careful, esp as to fine detail',
    'palpable': 'easily perceived by the senses or the mind; obvious',
    'paltry': 'insignificant; meagre',
    'panacea': 'a remedy for all diseases or ills',
    'panache': 'a dashing manner; style; swagger',
    'paradigmatic': 'of or relating to the set of all the inflected forms of a '
                 'word or a systematic arrangement displaying these forms',
    'paradoxical': 'seemingly absurd or self-contradictory, although true',
    'paragon': 'a model of excellence; pattern',
    'parochial': 'narrow in outlook or scope; provincial',
    'parsimonious': 'extremely reluctant to spend money; niggardly',
    'partial': 'relating to only a part; not general or complete',
    'passable': 'adequate, fair, or acceptable',
    'passive': 'not active or not participating perceptibly in an activity, '
            'organization, etc',
    'patent': 'a government grant to an inventor assuring him the sole right to '
           'make, use, and sell his invention for a limited period',
    'patronize': 'to behave or treat in a condescending way',
    'peccadillo': 'a petty sin or trifling fault',
    'peculiar': 'strange or unusual; odd',
    'pedantic': 'of, relating to, or characterized by pedantry',
    'pedestrian': 'a person travelling on foot; walker',
    'pejorative': 'having an unpleasant or disparaging connotation',
    'pellucid': 'transparent or translucent',
    'penchant': 'a strong inclination or liking; bent or taste',
    'penetrating': 'tending to or able to penetrate',
    'pensive': 'deeply or seriously thoughtful, often with a tinge of sadness',
    'penurious': 'niggardly with money',
    'perennial': 'lasting throughout the year or through many years',
    'perfidy': 'a perfidious act',
    'perfunctory': 'done superficially, only as a matter of routine; careless or '
                'cursory',
    'perilous': 'very hazardous or dangerous',
    'peripheral': 'not relating to the most important part of something; '
               'incidental, minor, or superficial',
    'pernicious': 'wicked or malicious',
    'perpetrate': 'to perform or be responsible for',
    'perpetuate': 'to cause to continue or prevail',
    'perseverance': 'continued steady belief or efforts, withstanding '
                 'discouragement or difficulty; persistence',
    'pertinacious': 'doggedly resolute in purpose or belief; unyielding',
    'pertinent': 'relating to the matter at hand; relevant',
    'pervasive': 'pervading or tending to pervade',
    'petulant': 'irritable, impatient, or sullen in a peevish or capricious way',
    'philistine': 'a person who is unreceptive to or hostile towards culture, the '
               'arts, etc; a smug boorish person',
    'phlegmatic': 'having a stolid or unemotional disposition',
    'phony': 'homicide ▪ murder ▪ felony murder ▪ manslaughter ▪ negligent '
          'homicide ▪ vehicular homicide crimes against property ▪ arson ▪ '
          'blackmail ▪ burglary ▪ embezzlement ▪ extortion ▪ false pretenses ▪ '
          'fraud ▪ larceny ▪ possessing stolen property ▪ robbery ▪ theft '
          'crimes against justice ▪ compounding ▪ misprision ▪ obstruction ▪ '
          'perjury ▪ malfeasance in office ▪ perverting the course of justice '
          'defences to liability ▪ automatism ▪ consent ▪ defence of property '
          '▪ diminished responsibility ▪ duress ▪ entrapment ▪ ignorantia '
          'juris non excusat ▪ infancy ▪ insanity ▪ justification ▪ mistake ▪ '
          'necessity ▪ provocation ▪ self-defence other common law areas ▪ '
          'contracts ▪ evidence ▪ property ▪ torts ▪ wills, trusts and estates '
          'portals ▪ criminal justice ▪ law v t e part of the common law '
          'series tort law',
    'picturesque': 'visually pleasing, esp in being striking or vivid',
    'pious': 'having or expressing reverence for a god or gods; religious; devout',
    'piquant': 'having an agreeably pungent or tart taste',
    'pithy': 'terse and full of meaning or substance',
    'placate': 'to pacify or appease',
    'placid': 'having a calm appearance or nature',
    'plaintive': 'expressing melancholy; mournful',
    'plastic': 'made of ',
    'platitude': 'a trite, dull, or obvious remark or statement; a commonplace',
    'plausible': 'apparently reasonable, valid, truthful, etc',
    'pliant': 'easily bent; supple',
    'plodding': 'slow and steady',
    'ploy': 'a manoeuvre or tactic in a game, conversation, etc; stratagem; '
         'gambit',
    'plucky': 'having or showing courage in the face of difficulties, danger, etc',
    'poignant': 'sharply distressing or painful to the feelings',
    'poise': 'composure or dignity of manner',
    'polarize': 'to acquire or cause to acquire polarity',
    'polemical': 'of or involving dispute or controversy',
    'polymath': 'a person of great and varied learning',
    'pomposity': 'vain or ostentatious display of dignity or importance',
    'portend': 'to give warning of; predict or foreshadow',
    'posturing': 'false behaviour in order to impress or deceive people',
    'potent': 'possessing great strength; powerful',
    'precarious': 'liable to failure or catastrophe; insecure; perilous',
    'precipitate': 'to cause to happen too soon or sooner than expected; bring on',
    'precipitous': 'resembling a precipice or characterized by precipices',
    'preclude': 'to exclude or debar',
    'precocious': 'ahead in development, such as the mental development of a '
               'child',
    'predicament': 'a perplexing, embarrassing, or difficult situation',
    'predilection': 'a predisposition, preference, or bias',
    'prefigure': 'to represent or suggest in advance',
    'premeditate': 'to plan or consider beforehand',
    'presage': 'an intimation or warning of something about to happen; portent; '
            'omen',
    'prescient': 'displaying knowledge of events before they take place; '
              'prophetic',
    'prescribe': 'to lay down as a rule or directive',
    'presumptuous': 'characterized by presumption or tending to presume; bold; '
                 'forward',
    'pretentious': 'making claim to distinction or importance, esp undeservedly',
    'prevail': 'often foll by over or against to prove superior; gain mastery',
    'prevaricate': 'to speak or act falsely or evasively with intent to deceive',
    'prime': 'first in quality or value; first-rate',
    'pristine': 'of or involving the earliest period, state, etc; original',
    'probity': 'confirmed integrity; uprightness',
    'proclivity': 'a tendency or inclination',
    'prodigal': 'recklessly wasteful or extravagant, as in disposing of goods or '
             'money',
    'prodigious': 'vast in size, extent, power, etc',
    'proficient': 'having great facility ; skilled',
    'profligate': 'shamelessly immoral or debauched',
    'profound': 'penetrating deeply into subjects or ideas',
    'profundity': 'the quality or state of penetrating deeply into subjects or '
               'ideas',
    'profuse': 'plentiful, copious, or abundant',
    'proliferate': 'to grow or reproduce rapidly',
    'prolix': 'so long as to be boring; verbose',
    'propagate': 'to reproduce or cause to reproduce; breed',
    'propensity': 'a natural tendency or disposition',
    'prophetic': 'of or relating to a prophet or prophecy',
    'propitiate': 'to appease or make well disposed; conciliate',
    'propitious': 'favourable; auguring well',
    'propriety': 'the quality or state of being appropriate or fitting',
    'prosaic': 'lacking imagination',
    'providential': 'relating to, characteristic of, or presumed to proceed from '
                 'or as if from divine providence',
    'provincial': 'of or connected with a province',
    'provocative': 'acting as a stimulus or incitement, esp to anger or sexual '
                'desire; provoking',
    'prowess': 'outstanding or superior skill or ability',
    'proxy': 'a person authorized to act on behalf of someone else; agent',
    'prudent': "discreet or cautious in managing one's activities; circumspect",
    'prurient': 'unusually or morbidly interested in sexual thoughts or practices',
    'puerile': 'exhibiting silliness; immature; trivial',
    'pugnacious': 'readily disposed to fight; belligerent',
    'punctilious': 'paying scrupulous attention to correctness in etiquette',
    'qualm': 'a sudden feeling of sickness or nausea',
    'quandary': 'a situation or circumstance that presents problems difficult to '
             'solve; predicament; dilemma',
    'quarantine': 'a period of isolation or detention, esp of persons or animals '
               'arriving from abroad, to prevent the spread of disease, '
               'usually consisting of the maximum known incubation period of '
               'the suspected disease',
    'quash': 'to subdue forcefully and completely; put down; suppress',
    'querulous': 'inclined to make whining or peevish complaints',
    'quibble': 'to make trivial objections; prevaricate',
    'quiescent': 'quiet, inactive, or dormant',
    'quirky': 'peculiarly individual or unconventional',
    'quixotic': 'preoccupied with an unrealistically optimistic or chivalrous '
             'approach to life; impractically idealistic',
    'radical': 'of, relating to, or characteristic of the basic or inherent '
            'constitution of a person or thing; fundamental',
    'raillery': 'light-hearted satire or ridicule; banter',
    'ramble': 'to stroll about freely, as for relaxation, with no particular '
           'direction',
    'ramification': 'the act or process of ramifying or branching out',
    'rampant': 'unrestrained or violent in behaviour, desire, opinions, etc',
    'rapacious': 'practising pillage or rapine',
    'rational': 'using reason or logic in thinking out a problem',
    'ravage': 'to cause extensive damage to',
    'recant': 'to repudiate or withdraw, esp formally in public',
    'recapitulate': 'to restate the main points of ; summarize',
    'reconcile': 'usually foll by to to make no longer opposed; cause to '
              'acquiesce in something unpleasant',
    'recondite': 'requiring special knowledge to be understood; abstruse',
    'recourse': 'the act of resorting to a person, course of action, etc, in '
             'difficulty or danger',
    'recrudescent': 'breaking out or appearing again after a period of dormancy; '
                 'recurring',
    'redoubtable': 'to be feared; formidable',
    'redundant': 'surplus to requirements; unnecessary or superfluous',
    'refine': 'to make or become free from impurities, sediment, or other foreign '
           'matter; purify',
    'reflect': 'to undergo or cause to undergo a process in which light, other '
            'electromagnetic radiation, sound, particles, etc, are thrown back '
            'after impinging on a surface',
    'refute': 'to prove of to be false or incorrect; disprove',
    'regress': 'to return or revert, as to a former place, condition, or mode of '
            'behaviour',
    'reiterate': 'to say or do again or repeatedly',
    'relegate': 'to move to a position of less authority, importance, etc; demote',
    'relent': "to change one's mind about some decided course, esp a harsh one; "
           'become more mild or amenable',
    'relinquish': 'to give up ; abandon',
    'relish': 'to savour or enjoy to the full',
    'remarkable': 'worthy of note or attention',
    'remedial': 'affording a remedy; curative',
    'remote': 'located far away; distant',
    'remuneration': 'the act of remunerating',
    'render': 'to present or submit for payment, approval, or action',
    'renege': 'often foll by on to go back',
    'renounce': 'to give up, esp by formal announcement',
    'repercussion': 'a result or consequence, esp one that is somewhat removed '
                 'from the action or event which precipitated it',
    'repertoire': 'all the plays, songs, operas, or other works collectively that '
               'a company, actor, singer, dancer, etc, has prepared and is '
               'competent to perform',
    'replenish': 'to make full or complete again by supplying what has been used '
              'up or is lacking',
    'reproach': 'to impute blame to for an action or fault; rebuke',
    'reprobate': 'morally unprincipled; depraved',
    'repudiate': 'to reject the authority or validity of; refuse to accept or '
              'ratify',
    'repugnant': 'repellent to the senses; causing aversion',
    'resent': 'to feel bitter, indignant, or aggrieved at',
    'residual': 'of, relating to, or designating a residue or remainder; '
             'remaining; left over',
    'resilient': 'capable of regaining its original shape or position after '
              'bending, stretching, compression, or other deformation; elastic',
    'resolute': 'firm in purpose or belief; steadfast',
    'resolve': 'to decide or determine firmly',
    'resourceful': 'ingenious, capable, and full of initiative, esp in dealing '
                'with difficult situations',
    'restive': 'restless, nervous, or uneasy',
    'reticent': 'not open or communicative',
    'retiring': 'shunning contact with others; shy',
    'retrench': 'to reduce or curtail ; economize',
    'rhetoric': 'the study of the technique of using language effectively',
    'rigor': 'a sudden feeling of chilliness, often accompanied by shivering: it '
          'sometimes precedes a fever',
    'robust': 'strong in constitution; hardy; vigorous',
    'rudimentary': 'basic; fundamental; not elaborated or perfected',
    'ruminate': 'to chew',
    'sacrosanct': 'very sacred or holy; inviolable',
    'sadistic': 'gaining pleasure or sexual gratification from the infliction of '
             'pain and mental suffering on another person; inflicting pain and '
             'mental suffering',
    'sagacious': 'having or showing sagacity; wise',
    'salubrious': 'conducive or favourable to health; wholesome',
    'salutary': 'promoting or intended to promote an improvement or beneficial '
             'effect',
    'sanctimonious': 'affecting piety or making a display of holiness',
    'sanction': 'final permission; authorization',
    'sanguine': 'cheerful and confident; optimistic',
    'satirical': 'of, relating to, or containing satire',
    'scant': 'scarcely sufficient; limited',
    'scathing': 'harshly critical; scornful',
    'schism': 'the division of a group into opposing factions',
    'scintillating': 'sparkling; twinkling',
    'scorn': 'open contempt or disdain for a person or thing; derision',
    'scrupulous': 'characterized by careful observation of what is morally right',
    'sedulous': 'constant or persistent in use or attention; assiduous; diligent',
    'self-indulgent': "tending to indulge one's own desires, etc",
    'sensational': 'causing or intended to cause intense feelings, esp of '
                'curiosity, horror, etc',
    'sentimental': 'tending to indulge the emotions excessively',
    'serene': 'peaceful or tranquil; calm',
    'sever': 'to put or be put apart; separate',
    'sham': 'anything that is not what it purports or appears to be',
    'shrewd': 'astute and penetrating, often with regard to business',
    'shrill': 'sharp and high-pitched in quality',
    'skirt': 'a garment hanging from the waist, worn chiefly by women and girls',
    'skittish': 'playful, lively, or frivolous',
    'slander': 'defamation in some transient form, as by spoken words, gestures, '
            'etc',
    'slight': 'small in quantity or extent',
    'slovenly': 'frequently or habitually unclean or untidy',
    'sluggish': 'lacking energy; inactive; slow-moving',
    'sober': 'not drunk',
    'soliloquy': 'the act of speaking alone or to oneself, esp as a theatrical '
              'device',
    'somnolent': 'drowsy; sleepy',
    'sophisticated': 'having refined or cultured tastes and habits',
    'sophistry': 'a method of argument that is seemingly plausible though '
              'actually invalid and misleading',
    'soporific': 'inducing sleep',
    'sound': 'based on reason, sense, or judgment',
    'spartan': 'of or relating to sparta or its citizens',
    'specious': 'apparently correct or true, but actually wrong or false',
    'speculate': 'to conjecture without knowing the complete facts',
    'spendthrift': 'a person who spends money in an extravagant manner',
    'sporadic': 'occurring at irregular points in time; intermittent',
    'spurious': 'not genuine or real',
    'spurn': 'to reject with contempt',
    'squander': 'to spend wastefully or extravagantly; dissipate',
    'staid': 'of a settled, sedate, and steady character',
    'stalwart': 'strong and sturdy; robust',
    'steadfast': 'fixed in intensity or direction; steady',
    'stern': 'showing uncompromising or inflexible resolve; firm, strict, or '
          'authoritarian',
    'stigmatize': 'to mark out or describe',
    'stoic': 'a person who maintains ',
    'stolid': 'showing little or no emotion or interest',
    'strife': 'angry or violent struggle; conflict',
    'stringent': 'requiring strict attention to rules, procedure, detail, etc',
    'subdued': 'cowed, passive, or shy',
    'subjective': 'belonging to, proceeding from, or relating to the mind of the '
               'thinking subject and not the nature of the object being '
               'considered',
    'subordinate': 'of lesser order or importance',
    'subservient': 'obsequious in behaviour or attitude',
    'subside': 'to become less loud, excited, violent, etc; abate',
    'substantiate': 'to establish as valid or genuine',
    'subsume': 'to incorporate under a comprehensive or inclusive classification '
            'or heading',
    'subtle': 'not immediately obvious or comprehensible',
    'subvert': 'to bring about the complete downfall or ruin of',
    'superficial': 'of, relating to, being near, or forming the surface',
    'superfluous': 'exceeding what is sufficient or required',
    'supersede': 'to take the place of ; supplant',
    'supplant': 'to take the place of, often by trickery or force',
    'supple': 'bending easily without damage',
    'supplicate': 'to make a humble request to ; plead',
    'suppress': 'to put an end to; prohibit',
    'surmount': 'to prevail over; overcome',
    'surreptitious': 'done, acquired, etc, in secret or by improper means',
    'surrogate': 'a person or thing acting as a substitute',
    'suspect': 'to believe guilty of a specified offence without proof',
    'swindle': 'to cheat of money, etc; defraud',
    'synoptic': 'of or relating to a synopsis',
    'tacit': 'implied or inferred without direct expression; understood',
    'taciturn': 'habitually silent, reserved, or uncommunicative',
    'tact': 'a sense of what is fitting and considerate in dealing with others, '
         'so as to avoid giving offence or to win good will; discretion',
    'tangential': 'of, being, relating to, or in the direction of a tangent',
    'tangible': 'capable of being touched or felt; having real substance',
    'tantalizing': 'teasing; frustratingly tempting, as by being inaccessible, '
                'out of reach, etc',
    'tantamount': 'foll by to as good ; equivalent in effect',
    'tarnish': 'to lose or cause to lose the shine, esp by exposure to air or '
            'moisture resulting in surface oxidation; discolour',
    'tedious': 'causing fatigue or tedium; monotonous',
    'temerity': 'rashness or boldness',
    'temper': 'a frame of mind; mood or humour',
    'tempestuous': 'of or relating to a tempest',
    'temporal': 'of or relating to time',
    'tenable': 'able to be upheld, believed, maintained, or defended',
    'tendentious': 'having or showing an intentional tendency or bias, esp a '
                'controversial one',
    'tentative': 'provisional or experimental; conjectural',
    'tenuous': 'insignificant or flimsy',
    'tepid': 'slightly warm; lukewarm',
    'terse': 'neatly brief and concise',
    'thorough': 'carried out completely and carefully',
    'timorous': 'fearful or timid',
    'tirade': 'a long angry speech or denunciation',
    'token': 'an indication, warning, or sign of something',
    'torpor': 'a state of physical or mental inactivity; lethargy',
    'tortuous': 'twisted or winding',
    'tout': 'to solicit or hawk, esp in a brazen way',
    'tractable': 'easily controlled or persuaded',
    'tranquil': 'calm, peaceful or quiet',
    'transcend': 'to go above or beyond, as in degree or excellence',
    'transgression': 'a breach of a law, etc; sin or crime',
    'transient': 'for a short time only; temporary or transitory',
    'transitory': 'of short duration; transient or ephemeral',
    'treatise': 'a formal work on a subject, esp one that deals systematically '
             'with its principles and conclusions',
    'trenchant': 'keen or incisive',
    'trifling': 'insignificant or petty',
    'trivial': 'of little importance; petty or frivolous',
    'truculent': 'defiantly aggressive, sullen, or obstreperous',
    'turbid': 'muddy or opaque, as a liquid clouded with a suspension of '
           'particles',
    'turbulent': 'being in a state of turbulence',
    'turgid': 'swollen and distended; congested',
    'turpitude': 'base character or action; depravity',
    'ubiquitous': 'having or seeming to have the ability to be everywhere at '
               'once; omnipresent',
    'umbrage': 'displeasure or resentment; offence',
    'unadorned': 'not decorated; plain',
    'unalloyed': 'not mixed or intermingled with any other thing; pure',
    'undercut': 'to charge less than in order to obtain trade',
    'undermine': 'to wear away the bottom or base of',
    'underscore': 'to draw or score a line or mark under',
    'understated': 'not obvious; subtle',
    'universal': 'of, relating to, or typical of the whole of mankind or of '
              'nature',
    'unprecedented': 'having no precedent; unparalleled',
    'unravel': 'to reduce to separate strands',
    'unscrupulous': 'without scruples; unprincipled',
    'unseemly': 'not in good style or taste; unbecoming',
    'upbraid': 'to reprove or reproach angrily',
    'urbane': 'characterized by elegance or sophistication',
    'utilitarian': 'of or relating to ',
    'vacillate': "to fluctuate in one's opinions; be indecisive",
    'vacuous': 'containing nothing; empty',
    'valedictory': 'a farewell address or speech',
    'valor': 'Courage',
    'vanquish': 'to defeat or overcome in a battle, contest, etc; conquer',
    'vapid': 'bereft of strength, sharpness, flavour, etc; flat',
    'venal': 'easily bribed or corrupted; mercenary',
    'venerate': 'to hold in deep respect; revere',
    'veracity': 'truthfulness or honesty, esp when consistent or habitual',
    'verbose': 'using or containing an excess of words, so as to be pedantic or '
            'boring; prolix',
    'verisimilitude': 'the appearance or semblance of truth or reality; quality '
                   'of seeming true',
    'veritable': 'genuine or true; proper',
    'versatile': 'capable of or adapted for many different uses, skills, etc',
    'verve': 'great vitality, enthusiasm, and liveliness; sparkle',
    'vestigial': 'of, relating to, or being a vestige',
    'vexation': 'the act of vexing or the state of being vexed',
    'viable': 'capable of becoming actual, useful, etc; practicable',
    'vigilant': 'keenly alert to or heedful of trouble or danger, as while others '
             'are sleeping or unsuspicious',
    'vilify': 'to revile with abusive or defamatory language; malign',
    'virulent': 'extremely infective',
    'visionary': 'marked by vision or foresight',
    'vitality': 'physical or mental vigour, energy, etc',
    'vitiate': 'to make faulty or imperfect',
    'vivacious': 'full of high spirits and animation; lively or vital',
    'vociferous': 'characterized by vehemence, clamour, or noisiness',
    'volatile': 'capable of readily changing from a solid or liquid form to a '
             'vapour; having a high vapour pressure and a low boiling point',
    'wane': 'to decrease gradually in size, strength, power, etc',
    'wanting': 'lacking or absent; missing',
    'warranted': 'justified',
    'wary': 'watchful, cautious, or alert',
    'wayward': "wanting to have one's own way regardless of the wishes or good of "
            'others',
    'weary': 'tired or exhausted',
    'wheedle': 'to persuade or try to persuade by coaxing words, flattery, etc',
    'whimsical': 'spontaneously fanciful or playful',
    'willful': 'blindness, intentionally putting oneself in a position where '
            'oneself will be unaware of facts that would render oneself liable',
    'wily': 'characterized by or proceeding from wiles; sly or crafty',
    'wistful': 'sadly pensive, esp about something yearned for',
    'withstand': 'to stand up to forcefully; resist',
    'woeful': 'expressing or characterized by sorrow',
    'xenophobic': 'having or showing a hatred or fear of foreigners or strangers '
               'or of their politics or culture',
    'yield': 'to give forth or supply, esp by cultivation, labour, etc; produce '
          'or bear',
    'zealous': 'filled with or inspired by intense enthusiasm or zeal; ardent; '
            'fervent',
    'zenith': 'the point on the celestial sphere vertically above an observer'
}